Build cjdroute-init binary in android_do

diff --git a/android_do b/android_do
--- a/android_do
+++ b/android_do
@@ -66,6 +66,7 @@ declare -a TARGET_ARCH=("arm" "aarch64" "x64")
 declare -a EABI=("androideabi" "android" "android")
 declare -a PLATFORM=(16 21 16)
 declare -a TOOLCHAIN=("arm-linux-androideabi-4.9" "aarch64-linux-android-4.9" "x86-4.9") 
+declare -a ARTIFACT=("cjdroute-init" "cjdroute")
 
 for i in {0..2}
 do
@@ -95,22 +96,29 @@ do
     echo Compiler CFLAGS: $CFLAGS
     echo Compiler LDFLAGS: $LDFLAGS
     time ./do
-    cp cjdroute $(pwd)/build_android/out/${APP_ABI[$i]}/ || ret=$?
 
-    if [ "$ret" != "" ] && [ "$ret" != "0" ]; then
-      echo -e "\e[1;31mCopying ${APP_ABI[$i]} binary failed, non zero status returned - $ret\e[0m"
-      exit 1
-    else
-      echo -e "\e[1;32mCopied ${APP_ABI[$i]} successfully\e[0m"
-    fi
+    for j in {0..1}
+    do
+        cp ${ARTIFACT[$j]} $(pwd)/build_android/out/${APP_ABI[$i]}/ || ret=$?
 
-    rm cjdroute
+        if [ "$ret" != "" ] && [ "$ret" != "0" ]; then
+          echo -e "\e[1;31mCopying ${APP_ABI[$i]} ${ARTIFACT[$j]} binary failed, non zero status returned - $ret\e[0m"
+          exit 1
+        else
+          echo -e "\e[1;32mCopied ${APP_ABI[$i]} ${ARTIFACT[$j]} successfully\e[0m"
+        fi
+
+        rm ${ARTIFACT[$j]}
+    done
 done
 
 echo -e "\n\e[1;34mOutput:\e[0m"
 for i in {0..2}
 do
-    echo -e   "\e[1;34m        $(pwd)/build_android/out/${APP_ABI[$i]}/cjdroute\e[0m"
+    for j in {0..1}
+    do
+        echo -e   "\e[1;34m        $(pwd)/build_android/out/${APP_ABI[$i]}/${ARTIFACT[$j]}\e[0m"
+    done
 done
 
 exit $ret
