Update android_do

diff --git a/android_do b/android_do
--- a/android_do
+++ b/android_do
@@ -4,7 +4,6 @@
 NDK=/bad/path/to/android-ndk-r10e/
 BUILD_PATH=$(pwd)/build_android
 #if you have cjdns android app somewhere else then change it
-PROJECT_PATH=$BUILD_PATH/cjdns-android
 NDK_VERSION="android-ndk-r10e"
 
 case $(uname -s) in
@@ -19,21 +18,22 @@ case $(uname -s) in
         ;;
 esac
 
+cpu_arch="$(uname -m)"
+[[ -z "$cpu_arch" ]] && {
+    echo "ERROR: NO CPU ARCHITECTURE DETECTED"
+    exit 1
+}
+[[ "$cpu_arch" = "i686" ]] \
+    && cpu_arch="x86"
+
 android_log=android_build_$$.log
 enabled_log=${LOG}
 
 mkdir $BUILD_PATH
 
-if [ "$NDK" == "/bad/path/to/android-ndk-r10d/" ]; then
+if [ "$NDK" == "/bad/path/to/android-ndk-r10e/" ]; then
   if [ ! -d $BUILD_PATH/$NDK_VERSION/ ]; then
     echo "NDK path is not specified. Downloading it..."
-    cpu_arch="$(uname -m)"
-    [[ -z "$cpu_arch" ]] && {
-        echo "ERROR: NO CPU ARCHITECTURE DETECTED"
-        exit 1
-    }
-    [[ "$cpu_arch" = "i686" ]] \
-        && cpu_arch="x86"
 
     NDK=$BUILD_PATH/$NDK_VERSION/
 
@@ -57,55 +57,71 @@ if [ "$NDK" == "/bad/path/to/android-ndk-r10d/" ]; then
   fi
 fi
 
-$NDK/build/tools/make-standalone-toolchain.sh --platform=android-21 --toolchain=arm-linux-androideabi-4.9 --install-dir=$BUILD_PATH/arm-linux-androideabi/ --system=${TYPE}-${cpu_arch}
+$NDK/build/tools/make-standalone-toolchain.sh --platform=android-21 --toolchain=arm-linux-androideabi-4.9 --install-dir=$BUILD_PATH/arm-${TYPE}-androideabi/ --system=${TYPE}-${cpu_arch}
+$NDK/build/tools/make-standalone-toolchain.sh --platform=android-21 --toolchain=x86-4.9 --install-dir=$BUILD_PATH/i686-${TYPE}-androideabi/ --system=${TYPE}-${cpu_arch}
 
 Seccomp_NO=1
 
-CROSS_COMPILE=$BUILD_PATH/arm-${TYPE}-androideabi/bin/arm-${TYPE}-androideabi-
-TARGET_ARCH=arm
-CC=${CROSS_COMPILE}gcc
-AR=${CROSS_COMPILE}ar
-RANLIB=${CROSS_COMPILE}ranlib
-CFLAGS=${CROSS_CFLAGS}
-LDFLAGS=${CROSS_LDFLAGS}
-gcc_version=$(${CC} --version)
-log_filename="${android_log%.*}"
-echo Using $gcc_version
+mkdir $(pwd)/android_out
+mkdir $(pwd)/android_out/armeabi-v7a
+mkdir $(pwd)/android_out/x86
 
+#arm build
+rm -rf build_linux
+
+export CROSS_COMPILE=$BUILD_PATH/arm-${TYPE}-androideabi/bin/arm-${TYPE}-androideabi-
+export TARGET_ARCH=arm
+export CROSS=${CROSS_COMPILE}
+export CC=${CROSS}gcc
+export AR=${CROSS}ar
+export RANLIB=${CROSS}ranlib
+export CFLAGS=${CROSS_CFLAGS}
+export LDFLAGS=${CROSS_LDFLAGS}
+gcc_version=$(${CC} --version)
+echo Using $gcc_version
 echo Compiler CC: $CC
 echo Compiler CFLAGS: $CFLAGS
 echo Compiler LDFLAGS: $LDFLAGS
+time ./do 
+cp cjdroute $(pwd)/android_out/armeabi-v7a/ || ret=$?
 
-time ./do
-
-if [ -d $ANDROID_HOME ]; then
-  ret="0"
-
-  if [ ! -d $PROJECT_PATH ]; then
-    git clone https://github.com/hyperboria/android $PROJECT_PATH || ret=$?
-  fi
-
-  echo $ret
-
-  if [ "$ret" == "" ] || [ "$ret" == "0" ]; then
-    unset ret
-    cp cjdroute $PROJECT_PATH/src/main/assets/armeabi-v7a/ || ret=$?
-
-    if [ "$ret" != "" ] && [ "$ret" != "0" ]; then
-      echo -e "\e[1;31mCopying failed, non zero status returned - $ret\e[0m"
-    else
-      echo -e "\e[1;32mCopied successfully\e[0m"
-
-      echo Building android app...
-      cd $PROJECT_PATH
-      echo "sdk.dir=$ANDROID_HOME" > $PROJECT_PATH/local.properties
-      ./gradlew installDebug
-    fi
-  fi
+if [ "$ret" != "" ] && [ "$ret" != "0" ]; then
+  echo -e "\e[1;31mCopying armeabi-v7a binary failed, non zero status returned - $ret\e[0m"
 else
-  echo -e "\n\e[1;33mAndroid SDK not found! Export ANDROID_HOME!\e[0m"
+  echo -e "\e[1;32mCopied armeabi-v7a successfully\e[0m"
 fi
 
-echo -e "\n\e[1;34mOutput: $(pwd)/cjdroute\e[0m"
+rm cjdroute
+
+#x86 build
+rm -rf build_linux
+
+export CROSS_COMPILE=$BUILD_PATH/i686-${TYPE}-androideabi/bin/i686-${TYPE}-android-
+export TARGET_ARCH=x64
+export CROSS=${CROSS_COMPILE}
+export CC=${CROSS}gcc
+export AR=${CROSS}ar
+export RANLIB=${CROSS}ranlib
+export CFLAGS=${CROSS_CFLAGS}
+export LDFLAGS=${CROSS_LDFLAGS}
+gcc_version=$(${CC} --version)
+echo Using $gcc_version
+echo Compiler CC: $CC
+echo Compiler CFLAGS: $CFLAGS
+echo Compiler LDFLAGS: $LDFLAGS
+time ./do
+
+cp cjdroute $(pwd)/android_out/x86/ || ret=$?
+
+if [ "$ret" != "" ] && [ "$ret" != "0" ]; then
+  echo -e "\e[1;31mCopying x86 binary failed, non zero status returned - $ret\e[0m"
+else
+  echo -e "\e[1;32mCopied x86 successfully\e[0m"
+fi
+
+rm cjdroute
+
+echo -e "\n\e[1;34mOutput: $BUILD_PATH/out/armeabi-v7a/cjdroute\e[0m"
+echo -e "\e[1;34m        $BUILD_PATH/out/x86/cjdroute\e[0m"
 
 exit $ret
