Fixed a ton of bugs, refactored, simplified cjdctl commands and updated README.md

diff --git a/contrib/android/cjdroid/files/cjdctl b/contrib/android/cjdroid/files/cjdctl
--- a/contrib/android/cjdroid/files/cjdctl
+++ b/contrib/android/cjdroid/files/cjdctl
@@ -1,77 +1,98 @@
 #!/system/bin/sh
 
+# Set the main directory for things to run (if changed, also change in cjdaemon and 99cjdroute)
 CJDPATH="/sdcard/cjdns"
 
-# Create the daemon folder if it doesn't exist, then kill the script if it's still missing
-if [ ! -e "$CJDPATH" ]; then mkdir -p "$CJDPATH"; fi
-if [ ! -d "$CJDPATH" ]; then exit 1; fi
+# Set the name of this script
+APPNAME=$(echo -n "$0" | grep -o -e "[^\/]*$")
 
+# Exit with an error if the user isn't root
+if [ ! $(whoami) = "root" ]; then
+    echo "Error: ${APPNAME} must be run as root"
+    exit 1
+fi
+
+# Create the daemon folder if it doesn't exist
+if [ ! -e "$CJDPATH" ]; then mkdir -p "$CJDPATH" || exit 1; fi
+
+# Source cjdaemon.conf to load user settings if it exists
 if [ -f "${CJDPATH}/cjdaemon.conf" ]; then source "${CJDPATH}/cjdaemon.conf"; fi
+
+# Set $CJDCFG to the default if it wasn't set by cjdaemon.conf
 if [ -z "$CJDCFG" ]; then CJDCFG="cjdroute.conf"; fi
 
-cjdstart() {
+# Create the lock file and start (or if running, restart) cjdaemon
+enable_cjdaemon() {
+    echo -n "${APPNAME}: Enabling cjdns... "
+
+    # Create the lock file, enabling cjdaemon
     if [ ! -f "${CJDPATH}/.lock" ]; then touch "${CJDPATH}/.lock"; fi
 
-    echo -n "starting cjdroute... "
-    if [ $(pgrep cjdroute | wc -l) -gt 0 ]; then echo "error: already running"; exit 1; fi
-    if [ ! -f "${CJDPATH}/${CJDCFG}" ]; then echo "error: ${CJDPATH}/${CJDCFG} does not exist"; exit 1; fi
-    cjdroute < "${CJDPATH}/${CJDCFG}" &> /dev/null 2>&1
-    if [ $(pgrep cjdroute | wc -l) -gt 0 ]; then echo "done!"; else echo "failed, cjdroute didn't start"; exit 1; fi
+    # If running, kill cjdaemon (it'll start cjdroute when restarted)
+    if [ -f "${CJDPATH}/.cjdaemon.pid" ]; then
+        if [ -d "/proc/$(cat ${CJDPATH}/.cjdaemon.pid)" ]; then
+            kill $(cat "${CJDPATH}/.cjdaemon.pid")
+            sleep 1
+        fi
+        rm "${CJDPATH}/.cjdaemon.pid"
+    fi
 
-    if [ -f "${CJDPATH}/.cjdaemon.pid" ]; then if [ -d "/proc/$(cat /sdcard/cjdns/.cjdaemon.pid)" ]; then exit 0; fi; fi
-    startcjdaemon
+    # Start cjdaemon (which will start cjdroute if the phone is awake)
+    cjdaemon &
+    sleep 1
+
+    # Exit successfully if cjdaemon started, otherwise exit with an error
+    if [ -f "${CJDPATH}/.cjdaemon.pid" ]; then
+        if [ -d "/proc/$(cat ${CJDPATH}/.cjdaemon.pid)" ]; then
+            echo "Done!"
+            exit 0
+        fi
+    fi
+    echo "Error! Couldn't start cjdaemon."
+    exit 1
 }
 
-cjdstop() {
+# Remove the lock file then kill cjdaemon and cjdroute if either is running
+disable_cjdaemon() {
+    echo -n "${APPNAME}: Disabling cjdns... "
+
+    # Remove the lock file, disabling cjdaemon
     if [ -f "${CJDPATH}/.lock" ]; then rm "${CJDPATH}/.lock"; fi
 
-    echo -n "stopping cjdroute... "
-    if [ $(pgrep cjdroute | wc -l) -eq 0 ]; then echo "error: not running"; exit 1; fi
-    killall cjdroute
-    sleep 1
-    if [ $(pgrep cjdroute | wc -l) -eq 0 ]; then echo "done!"; else echo "failed, cjdroute still running"; exit 1; fi
-}
-
-startcjdaemon() {
-    if [ ! -f "${CJDPATH}/.lock" ]; then touch "${CJDPATH}/.lock"; fi
-
-    echo -n "starting daemon... "
+    # If cjdaemon is running, kill it
     if [ -f "${CJDPATH}/.cjdaemon.pid" ]; then
-        if [ -d "/proc/$(cat /sdcard/cjdns/.cjdaemon.pid)" ]; then
-            echo "error: daemon already running"
+        if [ -d "/proc/$(cat ${CJDPATH}/.cjdaemon.pid)" ]; then
+            kill $(cat "${CJDPATH}/.cjdaemon.pid")
+            sleep 1
+        fi
+        rm "${CJDPATH}/.cjdaemon.pid"
+    fi
+
+    # If cjdroute is running, kill it
+    if [ $(pgrep cjdroute | wc -l) -gt 0 ]; then
+        killall cjdroute
+        sleep 1
+
+        if [ ! $(pgrep cjdroute | wc -l) -eq 0 ]; then
+            echo "Error! cjdroute still running"
             exit 1
         fi
     fi
-    cjdaemon &
-    sleep 1
-    if [ -f "${CJDPATH}/.cjdaemon.pid" ]; then if [ -d "/proc/$(cat /sdcard/cjdns/.cjdaemon.pid)" ]; then echo "done!"; else echo "error: daemon didn't start"; exit 1; fi; fi
+    echo "Done!"
 }
 
-stopcjdaemon() {
-    echo -n "stopping daemon... "
-    if [ ! -f "${CJDPATH}/.cjdaemon.pid" ]; then echo "error: pid file doesn't exist"; exit 1; fi
-    if [ -d "/proc/$(cat /sdcard/cjdns/.cjdaemon.pid)" ]; then
-        kill $(cat "${CJDPATH}/.cjdaemon.pid")
-        sleep 1
-        if [ ! -d "/proc/$(cat /sdcard/cjdns/.cjdaemon.pid)" ]; then echo "done!"; else echo "error: cjdaemon still running"; exit 1; fi
-    else
-        echo "error: cjdaemon isn't running"
-    fi
-    rm "${CJDPATH}/.cjdaemon.pid"
-    if [ -f "${CJDPATH}/.lock" ] || [ $(pgrep cjdroute | wc -l) -gt 0 ]; then cjdstop; fi
-}
-
-if [ "$1" = "start" ]; then
-    cjdstart
-elif [ "$1" = "stop" ]; then
-    cjdstop
-elif [ "$1" = "restart" ]; then
-    stop
-    start
-elif [ "$1" = "start-daemon" ]; then
-    startcjdaemon
-elif [ "$1" = "stop-daemon" ]; then
-    stopcjdaemon
-else
-    echo "$0 start|stop|restart|start-daemon|stop-daemon"
-fi
+# Parse commandline arguments and behave accordingly
+case "$1" in
+    e|enable)
+        enable_cjdaemon
+        ;;
+    d|disable)
+        disable_cjdaemon
+        ;;
+    *)
+        echo -e "Usage:\n\t${APPNAME} [option]\n"
+        echo -e "Options:"
+        echo -e "\te|enable: Start cjdns and enable at boot"
+        echo -e "\td|disable: Stop cjdns and disable at boot"
+        ;;
+esac
